<?php
$z[0]=Array("arcurl","",52,67);
$z[1]=Array("picname","",79,95);
$z[2]=Array("title","",102,116);
$z[3]=Array("arcurl","",229,244);
$z[4]=Array("fulltitle","",280,298);
$z[5]=Array("arcurl","",371,386);
$z[6]=Array("description","",388,435);
$z[6][4]['function']="cn_substr(@me,";
$z[6][4][')']="";
$z[7]=Array("arcurl","",486,501);
$z[8]=Array("typename","",509,526);
$z[9]=Array("pubdate","",540,615);
$z[9][4]['function']="GetDateMK(@me)";

?>