<div class="video-item">
                    <a href="[field:arcurl/]">
                        <img src="[field:picname/]" alt="">
                        <div class="info">
                            <p>[field:title/]</p>
                            <img src="images/play.png" alt="">
                        </div>
                        <div class="mask">
                            <img src="images/play2.png" alt="">
                        </div>
                    </a>
                </div>