<li>
                                <a href="[field:arcurl/]">
                                    <div class="img-box">
                                        <img src="[field:picname/]" alt="">
                                    </div>
                                    <div class="info">
                                        <h3>[field:title/]</h3>
                                        <p>[field:description ]...</p>
                                        <span>[field:pubdate function='strftime("%m-%d",@me)'/]</span>
                                    </div>
                                </a>
                            </li>