<li>
                    <div class="img"><a href="[field:arcurl/]"><img src="[field:picname/]" alt="[field:title/]"></a>
                    </div>
                    <div class="wenzhang">
                        <a href="[field:arcurl/]">
                            <h3>[field:title/]</h3>
                        </a>
                        <p><a href="[field:arcurl/]">[field:description function="cn_substr(@me,")/]...</a></p>
                        <div>
                            <a href="[field:arcurl/]"><span>[field:typename/]</span></a><i>[field:pubdate function="GetDateMK(@me)"/]</i>
                        </div>
                    </div>
                </li>