<div class="swiper-slide">
                                <a href="[field:arcurl/]"> <img src="[field:picname/]" alt=""> </a>
                                <h4>[field:title/]</h4>
                            </div>
                            {/dede:channel}

                            <!-- <div class="swiper-slide">
                                <a href="#"> <img src="{dede:global.cfg_templets_skin/}/images/swiper2.jpg" alt=""> </a>
                                <h4>习近平同志《论中国共产党历史》有声书</h4>
                            </div>
                            <div class="swiper-slide">
                                <a href="#"> <img src="{dede:global.cfg_templets_skin/}/images/swiper3.jpg" alt=""> </a>
                                <h4>习近平同志《论中国共产党历史》有声书</h4>
                            </div> -->



                        </div>
                        <div class="swiper-pagination"></div>
                        <div class="swiper-button-prev swiper-button-white"></div>
                        <div class="swiper-button-next swiper-button-white"></div>
                    </div>
                </div>
                <div class="tuijian-text">
                    <img src="{dede:global.cfg_templets_skin/}/images/tuijian.png" alt="">
                    <p> <a href="#"> 习近平同志《论中国共产党历史》有声书 </a> </p>
                </div>
            </div>
            <div class="p1-right">

                <div class="szyw list ">
                    <div>
                        {dede:type typeid='2'}
                        <h2>[field:typename /]</h2> <a href="[field:typelink /]">更多 ></a>
                        {/dede:type}
                    </div>
                    <ul>
                        {dede:arclist typeid='2' row='6' orderby ='rand' }
                        <li> <a href="[field:arcurl/]">[field:fulltitle/]</a> </li>