<?php
$z[0]=Array("arcurl","",56,71);
$z[1]=Array("picname","",83,99);
$z[2]=Array("title","",106,120);
$z[3]=Array("arcurl","",245,260);
$z[4]=Array("fulltitle","",300,318);
$z[5]=Array("arcurl","",399,414);
$z[6]=Array("description","",416,463);
$z[6][4]['function']="cn_substr(@me,";
$z[6][4][')']="";
$z[7]=Array("arcurl","",518,533);
$z[8]=Array("typename","",541,558);
$z[9]=Array("pubdate","",572,651);
$z[9][4]['function']="GetDateMK(@me)";

?>