<li>
                    <div class="img"><a href="#"><img src="[field:picname/]" alt=""></a></div>
                    <div class="wenzhang">
                        <a href="[field:arcurl/]"><h3>[field:title/]</h3></a>
                        <p><a href="[field:arcurl/]"> [field:description function="cn_substr(@me,50")/]...</a></p>
                        <div><a href="#"><span>党的动态</span></a><i>2021-1-1</i></div>
                    </div>
                </li>