<?php
$z[0]=Array("global","",85,117);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",181,213);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("arclist","\r\n                    <li class=\"two-list-a\"><a href=\"[field:arcurl/]\"> [field:title/]</a></li>\r\n                    ",516,701);
$z[2][4]['row']="4";
$z[2][4]['typeid']="4";
$z[2][4]['titlelen']="100";
$z[3]=Array("arclist","\r\n                    <li class=\"two-list-a\"><a href=\"[field:arcurl/]\"> [field:title/]</a></li>\r\n                    ",860,1045);
$z[3][4]['row']="4";
$z[3][4]['typeid']="5";
$z[3][4]['titlelen']="100";
$z[4]=Array("global","",1200,1232);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("arclist","\r\n        <div>\r\n            <a href=\"[field:arcurl/]\"><img src=\"[field:picname/]\" alt=\"\"></a>\r\n            <a href=\"[field:arcurl/]\"><img src=\"/A067477/templets/a067477/images/listtu5.png\" alt=\"\" class=\"tu-png\"></a>\r\n        </div>\r\n        <p>[field:title/] </p>\r\n        ",1445,1775);
$z[5][4]['idlist']="74";
$z[5][4]['titlelen']="200";
$z[6]=Array("arclist","\r\n                    <li><a href=\"[field:arcurl/]\">[field:title/]</a></li>\r\n                    ",1997,2166);
$z[6][4]['row']="4";
$z[6][4]['titlelen']="100";
$z[6][4]['orderby']="click";
$z[7]=Array("global","",2392,2424);
$z[7][4]['name']="cfg_templets_skin";

?>