<?php
$z[0]=Array("arcurl","",52,67);
$z[1]=Array("picname","",79,95);
$z[2]=Array("title","",102,116);
$z[3]=Array("arcurl","",229,244);
$z[4]=Array("title","",280,294);
$z[5]=Array("arcurl","",367,382);
$z[6]=Array("description","",384,431);
$z[6][4]['function']="cn_substr(@me,";
$z[6][4][')']="";
$z[7]=Array("arcurl","",482,497);
$z[8]=Array("typename","",505,522);
$z[9]=Array("pubdate","",536,611);
$z[9][4]['function']="GetDateMK(@me)";

?>