<?php
$z[0]=Array("arcurl","",116,131);
$z[1]=Array("picname","",143,159);
$z[2]=Array("title","",166,180);
$z[3]=Array("arcurl","",293,308);
$z[4]=Array("fulltitle","",344,362);
$z[5]=Array("arcurl","",435,450);
$z[6]=Array("description","",452,499);
$z[6][4]['function']="cn_substr(@me,";
$z[6][4][')']="";
$z[7]=Array("arcurl","",550,565);
$z[8]=Array("typename","",573,590);
$z[9]=Array("pubdate","",604,679);
$z[9][4]['function']="GetDateMK(@me)";

?>