<?php
$z[0]=Array("global","",1378,1410);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",1624,1656);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",1864,1896);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",2107,2139);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",2350,2382);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("global","",2593,2625);
$z[5][4]['name']="cfg_templets_skin";

?>