<?php
$z[0]=Array("global","",176,208);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",296,328);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",481,506);
$z[2][4]['name']="cfg_cmsurl";
$z[3]=Array("global","",765,797);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",938,965);
$z[4][4]['name']="cfg_indexurl";
$z[5]=Array("channel","\r\n            <li> <a href=\"[field:typelink/]\">[field:typename/]</a> </li>\r\n            ",1017,1147);
$z[5][4]['type']="top";

?>