<?php
$z[0]=Array("list","\r\n                <li>\r\n                    <div class=\"img\"><a href=\"#\"><img src=\"[field:picname/]\" alt=\"\"></a></div>\r\n                    <div class=\"wenzhang\">\r\n                        <a href=\"[field:arcurl/]\"><h3>[field:title/]</h3></a>\r\n                        <p><a href=\"[field:arcurl/]\"> [field:description function=\"cn_substr(@me,50\")/]...</a></p>\r\n                        <div><a href=\"#\"><span>党的动态</span></a><i>2021-1-1</i></div>\r\n                    </div>\r\n                </li>\r\n                ",395,938);

?>